# Generated by Django 5.2 on 2025-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birthday", "0005_congratulation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20, verbose_name="Тег")),
            ],
        ),
        migrations.AddField(
            model_name="birthday",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Удерживайте Ctrl для выбора нескольких вариантов",
                to="birthday.tag",
                verbose_name="Теги",
            ),
        ),
    ]
